version: '3.8'
services:
    postgresql:
        image: postgres:14.1
        volumes:
           - ./volumes/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - 127.0.0.1:5432:5432
